# fly.toml app configuration file generated for bookowl on 2023-07-21T13:23:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookowl"
primary_region = "arn"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
